name: Build Matrix

on:
  schedule:
    - cron: '0 0 * * */2'
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          check-latest: true
      - name: Install system dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pdm
      - name: Get pdm cache dir
        id: pdm-cache-dir
        run: |
          echo "dir=$(pdm config cache_dir)" >> $GITHUB_OUTPUT
      - name: Load pdm cache
        id: pdm-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.pdm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-pdm-${{ github.repository }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pdm-${{ github.repository }}-${{ hashFiles('pyproject.toml') }}
            ${{ runner.os }}-${{ matrix.python-version }}-pdm-${{ github.repository }}
        continue-on-error: true

      - name: Update the project
        id: update
        run: |
          echo "::group::Configure pdm"
          pdm config install.parallel true
          pdm config install.cache on
          pdm config
          pdm info
          pdm cache info
          echo "::endgroup::"

          echo "::group::Run pdm update"
          pdm sync -dG:all --no-self --clean
          pdm update --no-self
          pdm cache info
          echo "::endgroup::"

          echo "::group::Run pytest"
          pdm run test
          echo "::endgroup::"

      - name: Build with pdm
        id: build
        if: ${{ steps.update.outcome == 'success' }}
        run: pdm build -v --no-clean
