name: Daily Release

on:
  schedule:
    - cron: '0 1 * * */2'
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  release:
    environment: pdm_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3
        with:
          # persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Load pip cache
        id: pip-cache
        uses: actions/cache@main
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-pdm-pipx
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-pdm-
            ${{ runner.os }}-${{ matrix.python-version }}-pip-
      - name: Install system dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pdm
          pip install --upgrade pipx
          pipx install python-semantic-release
      - name: Get pdm cache dir
        id: pdm-cache-dir
        run: |
          echo "::set-output name=dir::$(pdm config cache_dir)"
      - name: Load pdm cache
        id: pdm-cache
        uses: actions/cache@main
        with:
          path: |
            ${{ steps.pdm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-pdm-${{ github.repository }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pdm-${{ github.repository }}-${{ hashFiles('pyproject.toml') }}
            ${{ runner.os }}-${{ matrix.python-version }}-pdm-${{ github.repository }}

      - name: Update the project
        id: update
        run: |
          echo "::group::Configure pdm"
          pdm config install.parallel true
          pdm config install.cache on
          pdm config
          pdm info
          pdm cache info
          echo "::endgroup::"

          echo "::group::Run pdm update"
          pdm sync -dG:all --no-self --clean
          pdm update --no-self
          pdm cache info
          echo "::endgroup::"

          echo "::group::Run pycln"
          pdm run style-pycln
          pdm run format-pycln
          echo "::endgroup::"

          echo "::group::Run isort"
          pdm run style-imports
          pdm run format-imports
          echo "::endgroup::"

          echo "::group::Run black"
          pdm run style
          pdm run format
          echo "::endgroup::"

          echo "::group::Run pytest"
          pdm run test
          echo "::endgroup::"

      - name: Run linting
        id: lint
        continue-on-error: true
        run: |
          pdm run lint-plugins
          # exit-zero treats all errors as warnings.
          pdm run lint --count --exit-zero --statistics || true

      - uses: codecov/codecov-action@master
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml # optional
          flags: unittests # optional
          verbose: true # optional (default = false)

      - name: Import GPG key
        if: ${{ steps.update.outcome == 'success' }}
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Setup git config
        if: ${{ steps.update.outcome == 'success' }}
        id: git
        run: |
          echo "::group::Setup git config"
          echo "=============================="
          git config user.name "Github Action"
          git config user.email action@github.com
          git config init.defaultBranch main
          echo "::endgroup::"

          echo "::group::Commit changes"
          git add .
          git status
          git commit -S -m "ci(github-actions): :construction_worker: update, format, lint, test" || true
          git pull --rebase
          echo "::endgroup::"

      - name: Github Release
        id: github_release
        if: ${{ steps.git.outcome == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: semantic-release publish

      # - name: Publish distribution 📦 to Test PyPI
      #   id: test_pypi
      #   if: ${{ steps.github_release.outcome == 'success' }}
      #   continue-on-error: true
      #   run: pdm publish --no-build -r testpypi -u __token__ -P ${{ secrets.TEST_PYPI_TOKEN }}

      # - name: Publish distribution 📦 to PyPI
      #   id: pypi
      #   if: ${{ steps.test_pypi.outcome == 'success' }}
      #   continue-on-error: true
      #   run: pdm publish --no-build -u __token__ -P ${{ secrets.PYPI_API_TOKEN }}
