name: Daily Release

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Get pip cache dir
        id: pip-cache-dir
        shell: bash
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - name: Load pip cache
        id: pip-cache
        uses: actions/cache@main
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-pdm-pycln
          restore-keys: |
            ${{ runner.os }}-pip-pdm-pycln
      - name: Install system dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pdm pycln pdm-publish commitizen
      - name: Get pdm cache dir
        id: pdm-cache-dir
        shell: bash
        run: |
          echo "::set-output name=dir::$(pdm config cache_dir)"
      - name: Load pdm cache
        id: pdm-cache
        uses: actions/cache@main
        with:
          path: |
            ${{ steps.pdm-cache-dir.outputs.dir }}
            ./.venv
          key: ${{ runner.os }}-pdm-${{ hashFiles('pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-

      - name: Update the project
        id: update
        shell: bash
        continue-on-error: true
        run: |
          eval $(pdm --pep582)
          pdm update --save-compatible --update-eager
          pdm install
          pdm config
          echo "=============================="
          echo "Run format/test/lint"
          echo "++++++++++++++++++++++++++++++"
          pdm run format-imports
          pdm run format
          pdm run test
          # Show the plugins used for linting
          pdm run lint-plugins
          # exit-zero treats all errors as warnings.
          pdm run lint --count --exit-zero --statistics || true
          pycln -a --diff tests src
          pycln -a tests src

      - name: Import GPG key
        if: ${{ steps.update.outcome == 'success' }}
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Setup git config
        if: ${{ steps.update.outcome == 'success' }}
        id: git
        shell: bash
        run: |
          echo "::set-output name=diff::$(git diff FETCH_HEAD --stat)"
          echo "=============================="
          echo "Setup git config"
          echo "++++++++++++++++++++++++++++++"
          git config user.name "Sam"
          git config user.email dev@samarthj.com
          git config user.signkey dev@samarthj.com
          git config commit.gpgsign true
          git config init.defaultBranch main
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          cz changelog
          git add .
          git status
          git commit -S -m "ci(github-actions): :construction_worker: updpkg" || true

      - name: Python Semantic Release
        if: ${{ steps.git.outcome == 'success' }}
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution 📦 to Test PyPI
        id: test_pypi
        if: ${{ steps.github_release.outcome == 'success' }}
        shell: bash
        run: |
          pdm publish -r testpypi --password ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Publish distribution 📦 to PyPI
        id: pypi
        if: ${{ steps.test_pypi.outcome == 'success' }}
        shell: bash
        run: |
          pdm publish --password ${{ secrets.PYPI_API_TOKEN }}
